connector_image: airbyte/source-stripe:dev
test_strictness_level: high
acceptance_tests:
  spec:
    tests:
      - spec_path: "source_stripe/spec.yaml"
  connection:
    tests:
      - config_path: "secrets/config.json"
        status: "succeed"
      - config_path: "secrets/connected_account_config.json"
        status: "succeed"
      - config_path: "integration_tests/invalid_config.json"
        status: "failed"
  discovery:
    tests:
      - config_path: "secrets/config.json"
        backward_compatibility_tests_config:
          disable_for_version: "0.1.37"
      - config_path: "secrets/connected_account_config.json"
        backward_compatibility_tests_config:
          disable_for_version: "0.1.37"
  basic_read:
    tests:
      - config_path: "secrets/config.json"
        empty_streams:
          - name: "external_account_bank_accounts"
            bypass_reason: "This stream can't be seeded in our sandbox account"
          - name: "external_account_cards"
            bypass_reason: "This stream can't be seeded in our sandbox account"
          - name: "products"
            bypass_reason: "This stream can't be seeded in our sandbox account"
        expect_records:
          path: "integration_tests/expected_records.jsonl"
          extra_fields: no
          exact_order: no
          extra_records: yes
        timeout_seconds: 7200
      - config_path: "secrets/connected_account_config.json"
        empty_streams:
          - name: "disputes"
            bypass_reason: "This stream can't be seeded in our sandbox account"
          - name: "external_account_cards"
            bypass_reason: "This stream can't be seeded in our sandbox account"
          - name: "checkout_sessions"
            bypass_reason: "This stream can't be seeded in our sandbox account"
          - name: "checkout_sessions_line_items"
            bypass_reason: "This stream can't be seeded in our sandbox account"
          - name: "events"
            bypass_reason: "This stream can't be seeded in our sandbox account"
          - name: "promotion_codes"
            bypass_reason: "This stream can't be seeded in our sandbox account"
          - name: "charges"
            bypass_reason: "This stream produces unique data every time it runs. Fields: receipt_url"
        expect_records:
          path: "integration_tests/expected_records_connected_account.jsonl"
          extra_fields: no
          exact_order: no
          extra_records: yes
        timeout_seconds: 3600
  incremental:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/non_invoice_line_items_catalog.json"
        future_state:
          future_state_path: "integration_tests/abnormal_state.json"
      - config_path: "secrets/connected_account_config.json"
        configured_catalog_path: "integration_tests/connected_account_configured_catalog.json"
        future_state:
          future_state_path: "integration_tests/abnormal_state.json"
  full_refresh:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/non_invoice_line_items_catalog.json"
        timeout_seconds: 3600
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/full_refresh_configured_catalog.json"
      - config_path: "secrets/connected_account_config.json"
        configured_catalog_path: "integration_tests/connected_account_configured_catalog.json"
        ignored_fields:
          "invoices":
            - invoice_pdf
            - hosted_invoice_url
