# See [Source Acceptance Tests](https://docs.airbyte.com/connector-development/testing-connectors/source-acceptance-tests-reference)
# for more information about how to configure these tests

connector_image: airbyte/source-tiktok-marketing:dev
cache_discovered_catalog: False
test_strictness_level: high
acceptance_tests:
  spec:
    tests:
      - spec_path: "integration_tests/spec.json"
  connection:
    tests:
      - config_path: "secrets/prod_config.json"
        status: "succeed"
      - config_path: "secrets/prod_config_with_day_granularity.json"
        status: "succeed"
      - config_path: "secrets/prod_config_with_lifetime_granularity.json"
        status: "succeed"
      - config_path: "secrets/new_config_prod.json"
        status: "succeed"
      - config_path: "secrets/config_oauth.json"
        status: "succeed"
      - config_path: "integration_tests/invalid_config.json"
        status: "failed"
      - config_path: "integration_tests/invalid_config_access_token.json"
        status: "failed"
      - config_path: "integration_tests/invalid_config_oauth.json"
        status: "failed"
  discovery:
    tests:
      - config_path: "secrets/prod_config.json"
        backward_compatibility_tests_config:
          disable_for_version: "1.0.1"
      - config_path: "secrets/prod_config_with_day_granularity.json"
        backward_compatibility_tests_config:
          disable_for_version: "1.0.1"
      - config_path: "secrets/prod_config_with_lifetime_granularity.json"
        backward_compatibility_tests_config:
          disable_for_version: "1.0.1"
      - config_path: "secrets/config.json"
        backward_compatibility_tests_config:
          disable_for_version: "1.0.1"
      - config_path: "secrets/new_config_prod.json"
        backward_compatibility_tests_config:
          disable_for_version: "1.0.1"
      - config_path: "secrets/config_oauth.json"
        backward_compatibility_tests_config:
          disable_for_version: "1.0.1"

  basic_read:
    tests:
      - config_path: "secrets/new_config_prod.json"
        expect_records:
          path: "integration_tests/new_prod_expected_records.jsonl"
        timeout_seconds: 1200
#        empty_streams:
#          - name: advertiser_ids
#            bypass_reason: "stream helper"
#      - config_path: "secrets/prod_config.json"
#        configured_catalog_path: "integration_tests/streams_reports_daily.json"
#        timeout_seconds: 1200
#      - config_path: "secrets/prod_config.json"
#        configured_catalog_path: "integration_tests/streams_reports_lifetime.json"
#        timeout_seconds: 1200
#      # Old style streams with granularity config (for < 0.1.13)
#      # Note: not needed to be tested separately in full and incremental tests, because code of
#      # these streams is called directly in new style streams
#      - config_path: "secrets/prod_config_with_day_granularity.json"
#        configured_catalog_path: "integration_tests/streams_with_day_granularity.json"
#        timeout_seconds: 1200
#      - config_path: "secrets/prod_config_with_lifetime_granularity.json"
#        configured_catalog_path: "integration_tests/streams_with_lifetime_granularity.json"
#        timeout_seconds: 1200

  incremental:
    tests:
      - config_path: "secrets/new_config_prod.json"
        configured_catalog_path: "integration_tests/new_prod_incremental_catalog.json"
        timeout_seconds: 7200
        future_state:
          future_state_path: "integration_tests/abnormal_state.json"
#      - config_path: "secrets/prod_config.json"
#        configured_catalog_path: "integration_tests/streams_reports_daily.json"
#        timeout_seconds: 7200
#        future_state_path: "integration_tests/abnormal_state.json"
#      # LIFETIME granularity: does not support incremental sync

  full_refresh:
    tests:
      - config_path: "secrets/new_config_prod.json"
        configured_catalog_path: "integration_tests/streams_basic.json"
        timeout_seconds: 7200
        ignored_fields: # Important: sometimes some streams does not return the same records in subsequent syncs
          "ad_groups":
            [
              "dayparting",
              "enable_search_result",
              "display_mode",
              "schedule_infos",
              "feed_type",
              "status",
            ]
#      - config_path: "secrets/prod_config.json"
#        configured_catalog_path: "integration_tests/streams_reports_daily.json"
#        timeout_seconds: 7200
#      - config_path: "secrets/prod_config.json"
#        configured_catalog_path: "integration_tests/streams_reports_lifetime.json"
#        timeout_seconds: 7200
