connector_image: airbyte/source-github:dev
test_strictness_level: "high"
acceptance_tests:
  spec:
    tests:
      - spec_path: "source_github/spec.json"
  connection:
    tests:
      - config_path: "secrets/config.json"
        status: "succeed"
      - config_path: "secrets/config_oauth.json"
        status: "succeed"
      - config_path: "integration_tests/invalid_config.json"
        status: "failed"
  discovery:
    tests:
      - config_path: "secrets/config.json"
      - config_path: "secrets/config_oauth.json"
  basic_read:
    tests:
      - config_path: "secrets/config.json"
        expect_records:
          path: "integration_tests/expected_records.jsonl"
          extra_fields: no
          exact_order: no
          extra_records: yes
        empty_streams:
          - name: assignees
            bypass_reason: "some reason"
          - name: branches
            bypass_reason: "some reason"
          - name: collaborators
            bypass_reason: "some reason"
          - name: comments
            bypass_reason: "some reason"
          - name: commit_comment_reactions
            bypass_reason: "some reason"
          - name: commit_comments
            bypass_reason: "some reason"
          - name: events
            bypass_reason: "Only events created within the past 90 days can be showed"
          - name: issue_comment_reactions
            bypass_reason: "some reason"
          - name: issue_events
            bypass_reason: "some reason"
          - name: issue_labels
            bypass_reason: "some reason"
          - name: issue_milestones
            bypass_reason: "some reason"
          - name: issue_reactions
            bypass_reason: "some reason"
          - name: issues
            bypass_reason: "some reason"
          - name: project_cards
            bypass_reason: "some reason"
          - name: project_columns
            bypass_reason: "some reason"
          - name: pull_request_comment_reactions
            bypass_reason: "some reason"
          - name: pull_request_commits
            bypass_reason: "some reason"
          - name: pull_request_stats
            bypass_reason: "some reason"
          - name: pull_requests
            bypass_reason: "some reason"
          - name: review_comments
            bypass_reason: "some reason"
          - name: reviews
            bypass_reason: "some reason"
          - name: stargazers
            bypass_reason: "some reason"
          - name: team_members
            bypass_reason: "some reason"
          - name: team_memberships
            bypass_reason: "some reason"
          - name: workflow_jobs
            bypass_reason: "some reason"
          - name: workflow_runs
            bypass_reason: "some reason"
          - name: workflows
            bypass_reason: "some reason"
  incremental:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"
        future_state:
          future_state_path: "integration_tests/abnormal_state.json"
        cursor_paths:
          comments: ["airbytehq/integration-test", "updated_at"]
          commit_comment_reactions:
            ["airbytehq/integration-test", "55538825", "created_at"]
          commit_comments: ["airbytehq/integration-test", "updated_at"]
          commits: ["airbytehq/integration-test", "master", "created_at"]
          deployments: ["airbytehq/integration-test", "updated_at"]
          events: ["airbytehq/integration-test", "created_at"]
          issue_comment_reactions:
            ["airbytehq/integration-test", "907296275", "created_at"]
          issue_events: ["airbytehq/integration-test", "created_at"]
          issue_milestones: ["airbytehq/integration-test", "updated_at"]
          issue_reactions: ["airbytehq/integration-test", "11", "created_at"]
          issues: ["airbytehq/integration-test", "updated_at"]
          project_cards:
            ["airbytehq/integration-test", "13167124", "17807006", "updated_at"]
          project_columns:
            ["airbytehq/integration-test", "13167124", "updated_at"]
          projects: ["airbytehq/integration-test", "updated_at"]
          pull_request_comment_reactions:
            ["airbytehq/integration-test", "699253726", "created_at"]
          pull_request_stats: ["airbytehq/integration-test", "updated_at"]
          pull_requests: ["airbytehq/integration-test", "updated_at"]
          releases: ["airbytehq/integration-test", "created_at"]
          repositories: ["airbytehq", "updated_at"]
          review_comments: ["airbytehq/integration-test", "updated_at"]
          reviews: ["airbytehq/integration-test", "updated_at"]
          stargazers: ["airbytehq/integration-test", "starred_at"]
          workflow_runs: ["airbytehq/integration-test", "updated_at"]
          workflows: ["airbytehq/integration-test", "updated_at"]
          workflow_jobs: ["airbytehq/integration-test", "completed_at"]
  full_refresh:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"
